services:
  hosta:
    build:
      context: .
      dockerfile: host.Dockerfile
    container_name: hosta
    command: sleep infinity
    privileged: true
    cap_add:
      - NET_ADMIN
    networks:
      lan:
        ipv4_address: 10.0.0.10

  hostb:
    build:
      context: .
      dockerfile: host.Dockerfile
    container_name: hostb
    command: sleep infinity
    privileged: true
    cap_add:
      - NET_ADMIN
    networks:
      lan:
        ipv4_address: 10.0.0.11

  r1:
    build:
      context: .
      dockerfile: router.Dockerfile
    container_name: r1
    command: sleep infinity
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
      - SYS_CHROOT
      - SYS_PTRACE
      - NET_BIND_SERVICE
    networks:
      lan:
        ipv4_address: 10.0.0.2
  
  r2:
    build:
      context: .
      dockerfile: router.Dockerfile
    container_name: r2
    command: sleep infinity
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
      - SYS_CHROOT
      - SYS_PTRACE
      - NET_BIND_SERVICE
    networks:
      lan:
        ipv4_address: 10.0.0.3

  r3:
    build:
      context: .
      dockerfile: router.Dockerfile
    container_name: r3
    command: sleep infinity
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
      - SYS_CHROOT
      - SYS_PTRACE
      - NET_BIND_SERVICE
    networks:
      lan:
        ipv4_address: 10.0.0.4

  r4:
    build:
      context: .
      dockerfile: router.Dockerfile
    container_name: r4
    command: sleep infinity
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
      - SYS_CHROOT
      - SYS_PTRACE
      - NET_BIND_SERVICE
    networks:
      lan:
        ipv4_address: 10.0.0.5

networks:
  lan:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24

